export const ACTUAL_EVENTS_FETCH = 'ACTUAL_EVENTS_FETCH';
export const ACTUAL_EVENTS_CLEAR_ERROR = 'ACTUAL_EVENTS_CLEAR_ERROR';
export const ACTUAL_EVENTS_SHOW_ERROR = 'ACTUAL_EVENTS_SHOW_ERROR';
export const ACTUAL_EVENTS_SHOW_LOADER = 'ACTUAL_EVENTS_SHOW_LOADER';
export const ACTUAL_EVENTS_HIDE_LOADER = 'ACTUAL_EVENTS_HIDE_LOADER';

export const EVENT_INFO_FETCH = 'EVENT_INFO_FETCH';
export const EVENT_INFO_CLEAR_ERROR = 'EVENT_INFO_CLEAR_ERROR';
export const EVENT_INFO_SHOW_ERROR = 'EVENT_INFO_SHOW_ERROR';
export const EVENT_INFO_SHOW_LOADER = 'EVENT_INFO_SHOW_LOADER';
export const EVENT_INFO_HIDE_LOADER = 'EVENT_INFO_HIDE_LOADER';

export const EVENT_PLAY_FETCH_TITLES = 'EVENT_PLAY_FETCH_TITLES';
export const EVENT_PLAY_FETCH_CHECKPOINT = 'EVENT_PLAY_FETCH_CHECKPOINT';
export const EVENT_PLAY_CLEAR_ERROR = 'EVENT_PLAY_CLEAR_ERROR';
export const EVENT_PLAY_SHOW_ERROR = 'EVENT_PLAY_SHOW_ERROR';
export const EVENT_PLAY_SHOW_LOADER = 'EVENT_PLAY_SHOW_LOADER';
export const EVENT_PLAY_HIDE_LOADER = 'EVENT_PLAY_HIDE_LOADER';

export const SCREEN_CHANGE = 'SCREEN_CHANGE';
