export const ACTUAL_EVENTS_FETCH = 'ACTUAL_EVENTS_FETCH';

export const EVENT_INFO_FETCH = 'EVENT_INFO_FETCH';

export const EVENT_PLAY_FETCH_TITLES = 'EVENT_PLAY_FETCH_TITLES';
export const EVENT_PLAY_FETCH_CHECKPOINT = 'EVENT_PLAY_FETCH_CHECKPOINT';

export const SCREEN_CHANGE = 'SCREEN_CHANGE';
export const SCREEN_RESET = 'SCREEN_RESET';

export const RUNCITY_API_CLEAR_ERROR = 'RUNCITY_API_CLEAR_ERROR';
export const RUNCITY_API_SHOW_ERROR = 'RUNCITY_API_SHOW_ERROR';
export const RUNCITY_API_SHOW_LOADER = 'RUNCITY_API_SHOW_LOADER';
export const RUNCITY_API_HIDE_LOADER = 'RUNCITY_API_HIDE_LOADER';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SIGNIN = 'USER_SIGNIN';
export const USER_CLEAR_ERROR = 'USER_CLEAR_ERROR';
export const USER_SHOW_ERROR = 'USER_SHOW_ERROR';
